#!/usr/bin/env python3
"""Self-host Anuphan from Google Fonts.

Fetches the Google Fonts CSS with a modern-Chrome UA (so we get woff2),
parses each @font-face block, downloads the woff2 for the subsets we care
about, and writes a fonts.css that points at local files.
"""
import os
import re
import urllib.request

CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Anuphan:wght@400;500;600;700&display=swap"
)
# A modern Chrome UA makes Google serve woff2 (its smallest, best-supported format).
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
WANT_SUBSETS = {"thai", "latin", "latin-ext"}
OUT_DIR = "assets/fonts"


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    css = fetch(CSS_URL)

    # Google prefixes each @font-face group with a comment naming the subset, e.g. /* thai */
    blocks = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
    # blocks -> ['', 'subset1', 'faceblock1', 'subset2', 'faceblock2', ...]
    out_css = []
    downloaded = []
    weight_re = re.compile(r"font-weight:\s*(\d+)")
    url_re = re.compile(r"url\((https://[^)]+\.woff2)\)")
    range_re = re.compile(r"unicode-range:\s*([^;]+);")

    for i in range(1, len(blocks), 2):
        subset = blocks[i].strip()
        face = blocks[i + 1]
        if subset not in WANT_SUBSETS:
            continue
        w = weight_re.search(face)
        u = url_re.search(face)
        ur = range_re.search(face)
        if not (w and u):
            continue
        weight = w.group(1)
        remote = u.group(1)
        unicode_range = ur.group(1).strip() if ur else None

        fname = f"anuphan-{weight}-{subset}.woff2"
        dest = os.path.join(OUT_DIR, fname)
        data = fetch(remote, binary=True)
        with open(dest, "wb") as f:
            f.write(data)
        downloaded.append((fname, len(data)))

        rule = [
            "@font-face {",
            "  font-family: 'Anuphan';",
            "  font-style: normal;",
            f"  font-weight: {weight};",
            "  font-display: swap;",
            f"  src: url('{OUT_DIR}/{fname}') format('woff2');",
        ]
        if unicode_range:
            rule.append(f"  unicode-range: {unicode_range};")
        rule.append("}")
        out_css.append("\n".join(rule))

    header = "/* Self-hosted Anuphan (Google Fonts) — generated by fetch_fonts.py */\n"
    with open("fonts.css", "w") as f:
        f.write(header + "\n".join(out_css) + "\n")

    print("Downloaded:")
    for name, size in downloaded:
        print(f"  {name}: {size/1024:.1f} KB")
    print(f"\nfonts.css written with {len(out_css)} @font-face rules")


if __name__ == "__main__":
    main()
